// Combined data for both graph view and map view
const data = {
    // Common places with both coordinate systems
    "places": [
        {"name": "ISBT", "safety_score": 7, "lat": 30.2901, "lng": 78.0574, "x": 100, "y": 100},
        {"name": "Clock Tower", "safety_score": 8, "lat": 30.3244, "lng": 78.0419, "x": 300, "y": 150},
        {"name": "Pacific Mall", "safety_score": 9, "lat": 30.3090, "lng": 78.0571, "x": 400, "y": 300},
        {"name": "FRI", "safety_score": 6, "lat": 30.2849, "lng": 77.9676, "x": 500, "y": 200},
        {"name": "Doon University", "safety_score": 7, "lat": 30.3186, "lng": 77.9610, "x": 200, "y": 250},
        {"name": "Paltan Bazaar", "safety_score": 5, "lat": 30.3259, "lng": 78.0450, "x": 550, "y": 100},
        {"name": "Rajpur Road", "safety_score": 8, "lat": 30.3382, "lng": 78.0549, "x": 150, "y": 350},
        {"name": "Clement Town", "safety_score": 6, "lat": 30.2669, "lng": 77.9937, "x": 350, "y": 50},
        
        {"name": "Mussoorie", "safety_score": 9, "lat": 30.4599, "lng": 78.0662},
        {"name": "Robber's Cave", "safety_score": 8, "lat": 30.3792, "lng": 78.0482},
        {"name": "Saharanpur Chowk", "safety_score": 7, "lat": 30.3155, "lng": 78.0322},
        {"name": "Prem Nagar", "safety_score": 6, "lat": 30.3082, "lng": 77.9366},
        {"name": "Vasant Vihar", "safety_score": 8, "lat": 30.3250, "lng": 78.0325},
        
        {"name": "Rajaji Park", "safety_score": 8, "lat": 30.1521, "lng": 78.3156},
        {"name": "Dalanwala", "safety_score": 7, "lat": 30.3342, "lng": 78.0627},
        {"name": "Ballupur", "safety_score": 6, "lat": 30.3201, "lng": 78.0123},
        {"name": "Race Course", "safety_score": 7, "lat": 30.3195, "lng": 78.0367},
        {"name": "Subhash Nagar", "safety_score": 6, "lat": 30.3078, "lng": 78.0491},
        {"name": "Jakhan", "safety_score": 8, "lat": 30.3621, "lng": 78.0802},
        {"name": "Majra", "safety_score": 5, "lat": 30.3089, "lng": 78.0012},
        {"name": "Kargi Chowk", "safety_score": 6, "lat": 30.2745, "lng": 78.0087},
        {"name": "Patel Nagar", "safety_score": 7, "lat": 30.3147, "lng": 78.0289},
        {"name": "Chakrata Road", "safety_score": 7, "lat": 30.3345, "lng": 78.0111}
    ],
    // Connections between places
    "connections": [
        {"from": "ISBT", "to": "Clock Tower"},
        {"from": "Clock Tower", "to": "Pacific Mall"},
        {"from": "Clock Tower", "to": "FRI"},
        {"from": "FRI", "to": "Doon University"},
        {"from": "ISBT", "to": "Pacific Mall"},
        {"from": "Doon University", "to": "Clement Town"},
        {"from": "Clock Tower", "to": "Paltan Bazaar"},
        {"from": "Paltan Bazaar", "to": "Rajpur Road"},
        {"from": "Rajpur Road", "to": "Clock Tower"},
        {"from": "Pacific Mall", "to": "Paltan Bazaar"},
        {"from": "Clock Tower", "to": "Doon University"},
        {"from": "Clement Town", "to": "FRI"},
        {"from": "ISBT", "to": "Clement Town"},
        {"from": "Clock Tower", "to": "Saharanpur Chowk"},
        {"from": "Saharanpur Chowk", "to": "Prem Nagar"},
        {"from": "Prem Nagar", "to": "FRI"},
        {"from": "Clock Tower", "to": "Robber's Cave"},
        {"from": "Robber's Cave", "to": "Mussoorie"},
        {"from": "Rajpur Road", "to": "Mussoorie"},
        {"from": "Vasant Vihar", "to": "Clock Tower"},
        {"from": "Vasant Vihar", "to": "Pacific Mall"},
        {"from": "Vasant Vihar", "to": "Saharanpur Chowk"},
        {"from": "Rajaji Park", "to": "ISBT"},
        {"from": "Rajaji Park", "to": "Kargi Chowk"},
        {"from": "Dalanwala", "to": "Rajpur Road"},
        {"from": "Dalanwala", "to": "Jakhan"},
        {"from": "Ballupur", "to": "FRI"},
        {"from": "Ballupur", "to": "Chakrata Road"},
        {"from": "Race Course", "to": "Clock Tower"},
        {"from": "Race Course", "to": "Patel Nagar"},
        {"from": "Subhash Nagar", "to": "Paltan Bazaar"},
        {"from": "Subhash Nagar", "to": "Patel Nagar"},
        {"from": "Jakhan", "to": "Rajpur Road"},
        {"from": "Majra", "to": "ISBT"},
        {"from": "Majra", "to": "Kargi Chowk"},
        {"from": "Kargi Chowk", "to": "FRI"},
        {"from": "Patel Nagar", "to": "Saharanpur Chowk"},
        {"from": "Chakrata Road", "to": "Ballupur"}
    ]
};